/// This file is auto-generated.
library;

import 'package:cli_tools/better_command_runner.dart' show CompletionTool;

const String _completionScript = r'''
# scloud completion                                        -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/bashly-framework/completely)
# Modifying it manually is not recommended

_scloud_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  # words the user already typed (excluding the command itself)
  local used=()
  if ((COMP_CWORD > 1)); then
    used=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi

  if [[ "${cur:0:1}" == "-" ]]; then
    # Completing an option: offer everything (including options)
    echo "$words"

  else
    # Completing a non-option: offer only non-options,
    # and don't re-offer ones already used earlier in the line.
    for word in $words; do
      [[ "${word:0:1}" == "-" ]] && continue

      local seen=0
      for u in "${used[@]}"; do
        if [[ "$u" == "$word" ]]; then
          seen=1
          break
        fi
      done
      ((!seen)) && result+=("$word")
    done

    echo "${result[*]}"
  fi
}

_scloud_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=()
  if ((COMP_CWORD > 0)); then
    compwords=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi
  local compline="${compwords[*]}"

  COMPREPLY=()

  case "$compline" in
    'db create-superuser'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db reset-password'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project invite'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project create'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project revoke'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db connection'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deploy'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'secret create'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain verify'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'secret delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain remove'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project link'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth logout'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db create-superuser'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db create-superuser'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain add'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'env delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'env update'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth login'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'env create'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db reset-password'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'user list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'env list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'settings'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'--write-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db reset-password'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'version'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project create'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project invite'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project revoke'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project invite'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain remove'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret create'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db connection'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project revoke'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deploy'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project delete'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'--file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project link'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'user'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--tool')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'domain remove'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret delete'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deploy'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret create'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db connection'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project list'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'--tool')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'project link'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'log'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth logout'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret create'*'--from-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'env'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain add'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env create'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env update'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth login'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret list'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth logout'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth login'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain add'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env delete'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env create'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'user list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env update'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'-f')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db create-superuser'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env update'*'--from-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'user list'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'completion generate'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env create'*'--from-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'env list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    *'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'env list'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'version'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db reset-password'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db create-superuser'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --username")" -- "$cur")
      ;;

    'deploy'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain add'*'--target')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "api insights web")" -- "$cur")
      ;;

    'launch'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --tool -t --exec-name -e --file -f")" -- "$cur")
      ;;

    'domain'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'user'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --tool -t --exec-name -e --write-dir -d")" -- "$cur")
      ;;

    'auth'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'log'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'user'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project invite'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db reset-password'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --username")" -- "$cur")
      ;;

    'auth'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project revoke'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret create'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deploy'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db connection'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain remove'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'log'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project link'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --enable-db --no-enable-db")" -- "$cur")
      ;;

    'project delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p")" -- "$cur")
      ;;

    'project revoke'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --user -u --role -r --all")" -- "$cur")
      ;;

    'secret list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project invite'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --user -u --role -r")" -- "$cur")
      ;;

    'auth logout'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    *'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain add'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name")" -- "$cur")
      ;;

    'domain remove'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name")" -- "$cur")
      ;;

    'domain add'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "api insights web")" -- "$cur")
      ;;

    'auth login'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db connection'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p")" -- "$cur")
      ;;

    'env create'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env update'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name --value --from-file")" -- "$cur")
      ;;

    'domain verify'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name")" -- "$cur")
      ;;

    'completion'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deploy'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --limit --utc --no-utc -u --deploy --list -l --build-log -b --output-overall-status")" -- "$cur")
      ;;

    'env delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    *'--scloud-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project link'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p")" -- "$cur")
      ;;

    'project list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --all")" -- "$cur")
      ;;

    'user list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p")" -- "$cur")
      ;;

    'secret list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p")" -- "$cur")
      ;;

    'auth logout'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'env delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name")" -- "$cur")
      ;;

    'env create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name --value --from-file")" -- "$cur")
      ;;

    'env update'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name --value --from-file")" -- "$cur")
      ;;

    'completion'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "generate install --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'domain add'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --name --target -t")" -- "$cur")
      ;;

    'version'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth login'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --timeout -t --persistent --no-persistent --browser --no-browser")" -- "$cur")
      ;;

    'project'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'user list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p")" -- "$cur")
      ;;

    'domain'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --analytics --no-analytics")" -- "$cur")
      ;;

    'env list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p")" -- "$cur")
      ;;

    'user'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'project'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create delete list link invite revoke --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'auth'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'env'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --concurrency -c --dry-run --no-dry-run")" -- "$cur")
      ;;

    'log'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "deploy --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'domain'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "add list remove verify --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'launch'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project --new-project --enable-db --no-enable-db --deploy --no-deploy")" -- "$cur")
      ;;

    'secret'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create list delete --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'db'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "login logout --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'user'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'log'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation --project -p --limit --utc --no-utc -u --recent -r --before --after --tail")" -- "$cur")
      ;;

    'env'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create list update delete --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    'db'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "connection create-superuser reset-password --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

    *'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completion version auth project deploy env domain log status secret db launch user settings --quiet -q --verbose -v --analytics --no-analytics -a --version --scloud-dir --project-dir -d --project-config-file --project-config-content --connection-timeout --skip-confirmation")" -- "$cur")
      ;;

  esac
} &&
  complete -F _scloud_completions scloud

# ex: filetype=sh

''';

/// Embedded script for command line completion for `completely`.
const completionScriptCompletely = (
  tool: CompletionTool.completely,
  script: _completionScript,
);
