/// This file is auto-generated.
library;

import 'package:cli_tools/better_command_runner.dart' show CompletionTool;

const String _completionScript = r'''
# scloud completion                                        -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/bashly-framework/completely)
# Modifying it manually is not recommended

_scloud_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  # words the user already typed (excluding the command itself)
  local used=()
  if ((COMP_CWORD > 1)); then
    used=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi

  if [[ "${cur:0:1}" == "-" ]]; then
    # Completing an option: offer everything (including options)
    echo "$words"

  else
    # Completing a non-option: offer only non-options,
    # and don't re-offer ones already used earlier in the line.
    for word in $words; do
      [[ "${word:0:1}" == "-" ]] && continue

      local seen=0
      for u in "${used[@]}"; do
        if [[ "$u" == "$word" ]]; then
          seen=1
          break
        fi
      done
      ((!seen)) && result+=("$word")
    done

    echo "${result[*]}"
  fi
}

_scloud_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=()
  if ((COMP_CWORD > 0)); then
    compwords=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi
  local compline="${compwords[*]}"

  COMPREPLY=()

  case "$compline" in
    'deployment build-secret unset'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret set'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user reset-password'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret unset'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment build-log'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user revoke'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user invite'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret set'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup restore'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth create-token'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret set'*'--from-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule unset'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup delete'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup create'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule show'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment show'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule set'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable unset'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password unset'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user create'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user reset-password'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project delete'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db connection'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain attach'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'context unset'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain verify'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain detach'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-log'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context show'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret set'*'--type')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "ssh")" -- "$cur")
      ;;

    'context list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable set'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'secret unset'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password set'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project link'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth logout'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'context set'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'secret list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user revoke'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user invite'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth login'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret unset'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret set'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth create-token'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth list'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup restore'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule unset'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret set'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup create'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup delete'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule show'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'--write-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'context'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment show'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule set'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db wipe'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment build-secret unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name")" -- "$cur")
      ;;

    'deploy'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project create'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user create'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password unset'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project delete'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable unset'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment build-secret list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'launch'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'secret'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule set'*'--frequency')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "daily weekly monthly")" -- "$cur")
      ;;

    'domain attach'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment build-secret set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name --value --from-file --type")" -- "$cur")
      ;;

    'domain verify'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context unset'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain detach'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db connection'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'--file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--tool')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'deployment build-secret'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project link'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable set'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret unset'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password set'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context show'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'--tool')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'auth logout'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user reset-password'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'log'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'context set'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password set'*'--from-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable set'*'--from-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'me'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth login'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret set'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deployment'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment build-log'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment build-secret'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "set list unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'auth list'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret set'*'--from-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain attach'*'--target')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "api insights web")" -- "$cur")
      ;;

    'completion generate'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'variable'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user reset-password'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --username")" -- "$cur")
      ;;

    'project user revoke'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'-f')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user invite'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db wipe'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    *'--project-config-file')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*'--plan')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "starter growth")" -- "$cur")
      ;;

    'completion install'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'db user'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth create-token'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment build-log'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --utc --no-utc -u --deploy")" -- "$cur")
      ;;

    'deploy'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup restore'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule unset'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user invite'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --user -u")" -- "$cur")
      ;;

    'db backup create'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule show'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --tool -t --exec-name -e --file -f")" -- "$cur")
      ;;

    'project user revoke'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --user -u")" -- "$cur")
      ;;

    'db backup delete'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment show'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --tool -t --exec-name -e --write-dir -d")" -- "$cur")
      ;;

    'deployment list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule set'*'-f')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "daily weekly monthly")" -- "$cur")
      ;;

    'db schedule set'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'db user create'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password unset'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup restore'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --snapshot")" -- "$cur")
      ;;

    'variable unset'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'log'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth create-token'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --expire-at --idle-ttl --no-idle-ttl")" -- "$cur")
      ;;

    'project delete'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name --expire-in --utc --no-utc -u")" -- "$cur")
      ;;

    'password list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain attach'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --snapshot")" -- "$cur")
      ;;

    'context unset'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain detach'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db connection'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule show'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'me'*'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain attach'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "api insights web")" -- "$cur")
      ;;

    'db schedule set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --frequency -f --day --hour --retention")" -- "$cur")
      ;;

    'deployment show'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --utc --no-utc -u --deploy --output-overall-status --await --no-await")" -- "$cur")
      ;;

    'secret unset'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'--output')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context show'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deployment list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --limit --utc --no-utc -u")" -- "$cur")
      ;;

    'context list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable set'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project link'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'--output')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password set'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name")" -- "$cur")
      ;;

    'project create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --plan --enable-db --no-enable-db")" -- "$cur")
      ;;

    'db user create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --username")" -- "$cur")
      ;;

    'variable unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name")" -- "$cur")
      ;;

    'project delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'db backup list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --utc --no-utc -u")" -- "$cur")
      ;;

    'secret list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context set'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth logout'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain attach'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name --target -t")" -- "$cur")
      ;;

    'variable list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'context unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'completion'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    *'--project-dir')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'deployment'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain detach'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name")" -- "$cur")
      ;;

    'db connection'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'secret set'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name")" -- "$cur")
      ;;

    'auth login'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list invite revoke --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'variable set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name --value --from-file")" -- "$cur")
      ;;

    'password set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name --value --from-file")" -- "$cur")
      ;;

    'db backup'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth list'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --all")" -- "$cur")
      ;;

    'secret unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name")" -- "$cur")
      ;;

    'context show'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'project link'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --dart-version")" -- "$cur")
      ;;

    'context list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'db schedule'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "set show unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'secret list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'variable'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'settings'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth logout'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --token-id --all")" -- "$cur")
      ;;

    'domain list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'password'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth login'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --time-limit --persistent --no-persistent")" -- "$cur")
      ;;

    'secret set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --name --value --from-file")" -- "$cur")
      ;;

    'completion'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "generate install --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'deployment'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "show list build-log build-secret --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'db wipe'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'context'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --utc --no-utc -u")" -- "$cur")
      ;;

    'domain'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create list delete restore --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'launch'*'-o')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deploy'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'-o')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'settings'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --analytics --no-analytics")" -- "$cur")
      ;;

    'variable'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list set unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'password'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list set unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'db wipe'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p")" -- "$cur")
      ;;

    'context'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list show set unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'db user'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create reset-password --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'version'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'project'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create delete list link user --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'auth'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'secret'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "set list unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'deploy'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --concurrency -c --wet-run --show-files --output -o --await --no-await --dart-version")" -- "$cur")
      ;;

    'launch'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --pre-deploy-scripts --no-pre-deploy-scripts --dart-version --concurrency -c --wet-run --show-files --output -o --await --no-await")" -- "$cur")
      ;;

    'log'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "attach list detach verify --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'me'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "login logout list create-token --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'log'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --project -p --limit --utc --no-utc -u --until --since --tail")" -- "$cur")
      ;;

    'db'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "connection user backup schedule wipe --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    'me'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

    *'-d')
      compopt -o filenames 2>/dev/null
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completion version auth me project context deploy variable domain log deployment secret password db launch settings --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes")" -- "$cur")
      ;;

  esac
} &&
  complete -F _scloud_completions scloud

# ex: filetype=sh

''';

/// Embedded script for command line completion for `completely`.
const completionScriptCompletely = (
  tool: CompletionTool.completely,
  script: _completionScript,
);
