/// This file is auto-generated.
library;

import 'package:cli_tools/better_command_runner.dart' show CompletionTool;

const String _completionScript = r'''
# scloud completion                                        -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/bashly-framework/completely)
# Modifying it manually is not recommended

_scloud_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  # words the user already typed (excluding the command itself)
  local used=()
  if ((COMP_CWORD > 1)); then
    used=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi

  if [[ "${cur:0:1}" == "-" ]]; then
    # Completing an option: offer everything (including options)
    echo "$words"

  else
    # Completing a non-option: offer only non-options,
    # and don't re-offer ones already used earlier in the line.
    for word in $words; do
      [[ "${word:0:1}" == "-" ]] && continue

      local seen=0
      for u in "${used[@]}"; do
        if [[ "$u" == "$word" ]]; then
          seen=1
          break
        fi
      done
      ((!seen)) && result+=("$word")
    done

    echo "${result[*]}"
  fi
}

_scloud_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=()
  if ((COMP_CWORD > 0)); then
    compwords=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")
  fi
  local compline="${compwords[*]}"

  COMPREPLY=()

  case "$compline" in
    'status deployment show'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user reset-password'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deployment list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deployment log'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file download'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user revoke'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user invite'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file upload'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'build secret unset'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup restore'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'build secret list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth create-token'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule unset'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth revoke-token'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deployment'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup create'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule show'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'build secret set'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule set'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'settings unset'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user create'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password unset'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage create'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable unset'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user reset-password'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment show'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user delete'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deployment list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain attach'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db connection'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deployment log'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file download'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain detach'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project show'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'settings set'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password set'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable set'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'build secret'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project link'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user revoke'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user invite'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status live'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth logout'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file upload'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth login'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'build secret unset'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment show'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db backup'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deployment list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db backup restore'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user reset-password'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build log'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build secret list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth list'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'auth create-token'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule unset'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth revoke-token'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment log'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build secret set'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup create'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file download'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db schedule show'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion install'*'--write-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db wipe'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule set'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'storage file upload'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password unset'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage create'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user create'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user revoke'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'launch'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project user invite'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'storage file delete'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'variable unset'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build secret set'*'--from-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'settings unset'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage delete'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'completion generate'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project create'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain detach'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'domain attach'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build secret unset'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'completion install'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db connection'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule set'*'--frequency')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "daily weekly monthly")" -- "$cur")
      ;;

    'project show'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'auth'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'build secret'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project link'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build secret list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db backup restore'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project user list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'completion generate'*'--tool')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'completion generate'*'--file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db user list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings set'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth revoke-token'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'variable set'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule unset'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password set'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'auth create-token'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'domain list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'--tool')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'log'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db backup create'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'status live'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup delete'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db schedule'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user reset-password'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule show'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'auth logout'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment show'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build secret set'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'completion'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password set'*'--from-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'variable set'*'--from-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status deployment log'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'me'*'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'db schedule set'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'storage file download'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth login'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings unset'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build log'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build secret set'*'--type')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "ssh")" -- "$cur")
      ;;

    'storage delete'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'storage create'*'--access')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "public private")" -- "$cur")
      ;;

    'storage create'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password unset'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db user create'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db user delete'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db backup'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project delete'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project create'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'auth list'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable unset'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'domain attach'*'--target')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "api insights web")" -- "$cur")
      ;;

    'domain attach'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project user invite'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user reset-password'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --username")" -- "$cur")
      ;;

    'project user revoke'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain detach'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'storage file upload'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain verify'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db connection'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'settings list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'settings'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'completion generate'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment show'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --utc --no-utc -u --deploy --output-overall-status --await --no-await")" -- "$cur")
      ;;

    'completion generate'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'storage file delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion generate'*'-f')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'password'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --limit --utc --no-utc -u")" -- "$cur")
      ;;

    'variable'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build secret unset'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project link'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project show'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password set'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'variable set'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build secret'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'settings set'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project create'*'--plan')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "starter growth")" -- "$cur")
      ;;

    *'--project-config-file')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db wipe'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion install'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completely carapace")" -- "$cur")
      ;;

    'storage file download'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --storage -s --path --output -o")" -- "$cur")
      ;;

    'storage'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'version'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment log'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --utc --no-utc -u --deploy")" -- "$cur")
      ;;

    'storage file'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'launch'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth logout'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'auth create-token'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth revoke-token'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule unset'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db backup restore'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status live'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'domain list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build secret list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user revoke'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --user -u")" -- "$cur")
      ;;

    'build'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --storage -s --path")" -- "$cur")
      ;;

    'db schedule show'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup create'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth login'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build secret set'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project user invite'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --user -u")" -- "$cur")
      ;;

    'completion generate'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --tool -t --exec-name -e --file -f")" -- "$cur")
      ;;

    'db backup delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file upload'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --storage -s --file -f --path --follow-symlinks")" -- "$cur")
      ;;

    'auth'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'build secret unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name")" -- "$cur")
      ;;

    'build log'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db schedule set'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule set'*'-f')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "daily weekly monthly")" -- "$cur")
      ;;

    'completion install'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --tool -t --exec-name -e --write-dir -d")" -- "$cur")
      ;;

    'auth list'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'db user delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'log'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project user list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'build secret list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'db backup list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --storage -s --path --tree -t --utc --no-utc -u")" -- "$cur")
      ;;

    'project delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup restore'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --snapshot")" -- "$cur")
      ;;

    'project create'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage delete'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'storage create'*'-a')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "public private")" -- "$cur")
      ;;

    'auth revoke-token'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --token-id")" -- "$cur")
      ;;

    'storage create'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth create-token'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --expire-at --idle-ttl --no-idle-ttl")" -- "$cur")
      ;;

    'variable unset'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status deployment'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "show list log --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'variable'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'settings'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password unset'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'settings unset'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user create'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --snapshot")" -- "$cur")
      ;;

    'project'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'domain attach'*'-t')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "api insights web")" -- "$cur")
      ;;

    'build secret set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name --value --from-file --type")" -- "$cur")
      ;;

    'db'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule show'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'db connection'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain detach'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name --expire-in --utc --no-utc -u")" -- "$cur")
      ;;

    'me'*'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain attach'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'domain verify'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db wipe'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'storage'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'settings set'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'password set'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db schedule set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --frequency -f --day --hour --retention")" -- "$cur")
      ;;

    'storage list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable set'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage file'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'domain'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'deploy'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project user'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'project link'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'launch'*'--output')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'deploy'*'--output')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'project show'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build secret'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db user create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --username")" -- "$cur")
      ;;

    'build'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'storage create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --storage -s --access -a")" -- "$cur")
      ;;

    'db user delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --username")" -- "$cur")
      ;;

    'variable unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name")" -- "$cur")
      ;;

    'db schedule'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --name")" -- "$cur")
      ;;

    'auth logout'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project create'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --plan --enable-db --no-enable-db")" -- "$cur")
      ;;

    'status live'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'storage delete'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --storage -s")" -- "$cur")
      ;;

    'db backup list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --utc --no-utc -u")" -- "$cur")
      ;;

    'password unset'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name")" -- "$cur")
      ;;

    'domain list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    *'--project-dir')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'completion'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'settings list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'domain verify'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name")" -- "$cur")
      ;;

    'auth login'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain detach'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name")" -- "$cur")
      ;;

    'db connection'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'domain attach'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name --target -t")" -- "$cur")
      ;;

    'variable list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'password list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'build secret'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "set list unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'log'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'storage file'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list upload download delete --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'db user list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --utc --no-utc -u")" -- "$cur")
      ;;

    'settings set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --name --value")" -- "$cur")
      ;;

    'project list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --all --utc --no-utc -u")" -- "$cur")
      ;;

    'password set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name --value --from-file")" -- "$cur")
      ;;

    'variable set'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --name --value --from-file --secret --no-secret")" -- "$cur")
      ;;

    'build log'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project show'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --utc --no-utc -u")" -- "$cur")
      ;;

    'project link'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --dart-version")" -- "$cur")
      ;;

    'db backup'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth list'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'project user'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list invite revoke --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'password'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'domain list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'db schedule'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "set show unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'me'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'auth logout'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --token-id --all")" -- "$cur")
      ;;

    'variable'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'status live'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --utc --no-utc -u --watch --interval")" -- "$cur")
      ;;

    'settings'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'completion'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "generate install --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'db user'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db wipe'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'project'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth login'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --time-limit --persistent --no-persistent")" -- "$cur")
      ;;

    'storage'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'version'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db backup'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create list delete restore --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'domain'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'-o')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'status'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'auth list'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --utc --no-utc -u")" -- "$cur")
      ;;

    'launch'*'-o')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")
      ;;

    'build log'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --utc --no-utc -u --deploy")" -- "$cur")
      ;;

    'launch'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'deploy'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'variable'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list set unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'settings'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list set unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    *'--format')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "text json yaml")" -- "$cur")
      ;;

    'password'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list set unset --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'db user'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create list reset-password delete --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'db wipe'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p")" -- "$cur")
      ;;

    'project'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "create delete list show link user --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'auth'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'storage'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "list create delete file --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'version'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'launch'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --pre-deploy-scripts --no-pre-deploy-scripts --dart-version --utc --no-utc -u --concurrency -c --wet-run --show-files --output -o --await --no-await")" -- "$cur")
      ;;

    'domain'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "attach list detach verify --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'deploy'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --concurrency -c --wet-run --show-files --redeploy --output -o --await --no-await --dart-version")" -- "$cur")
      ;;

    'status'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "live deployment --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'log'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'db'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'me'*'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'build'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "log secret --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'auth'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "login logout list create-token revoke-token --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    'log'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format --project -p --limit --utc --no-utc -u --until --since --tail --raw")" -- "$cur")
      ;;

    'db'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "connection user backup schedule wipe --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    *'-d')
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A directory -- "$cur")
      ;;

    'me'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "--quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_scloud_completions_filter "completion version auth me project deploy variable domain log status build password db storage launch settings --quiet -q --verbose -v --analytics --no-analytics -a --version --token --project-dir -d --project-config-file --timeout --yes --non-interactive --format")" -- "$cur")
      ;;

  esac
} &&
  complete -F _scloud_completions scloud

# ex: filetype=sh

''';

/// Embedded script for command line completion for `completely`.
const completionScriptCompletely = (
  tool: CompletionTool.completely,
  script: _completionScript,
);
