import 'dart:io';

import 'package:path/path.dart' as p;

/// Creates filtered copies of a project's `pubspec.lock`.
final class PubspecLockFilter {
  PubspecLockFilter._();

  static const _lockFileName = 'pubspec.lock';

  static const _generatedByPubLine = '# Generated by pub';
  static const _generatedByScloudLine = '# Generated by scloud';
  static const _demotedDependencyLine = '    dependency: transitive';

  /// Matches a package entry header under the `packages:` section
  /// (exactly two spaces of indent).
  static final _packageHeaderPattern = RegExp(r'^  ([^ \t:#][^:]*):\s*$');

  /// Reads `pubspec.lock` under [projectPath], writes a copy to
  /// [outputFilePath] with [packagesToRemove] omitted and [packagesToDemote]
  /// changed to `dependency: transitive`.
  /// Returns package names that remain in the copy but are not listed in
  /// [expectedRemainingPackages].
  static Set<String> createFilteredCopy({
    required final String projectPath,
    required final String outputFilePath,
    required final Set<String> packagesToRemove,
    required final Set<String> packagesToDemote,
    required final Set<String> expectedRemainingPackages,
  }) {
    final lockFile = File(p.join(projectPath, _lockFileName));
    final String content;
    try {
      content = lockFile.readAsStringSync();
    } on FileSystemException catch (e) {
      throw FormatException(
        'Failed to read pubspec.lock at `${lockFile.path}`: ${e.message}',
      );
    }

    final result = filter(
      content: content,
      packagesToRemove: packagesToRemove,
      packagesToDemote: packagesToDemote,
      expectedRemainingPackages: expectedRemainingPackages,
    );

    final (output, unexpectedPackages) = result;
    final outputFile = File(outputFilePath);
    try {
      outputFile.writeAsStringSync(output);
    } on FileSystemException catch (e) {
      throw FormatException(
        'Failed to write filtered pubspec.lock at `$outputFilePath`: '
        '${e.message}',
      );
    }

    return unexpectedPackages;
  }

  /// Filters the content of a pubspec.lock file with [packagesToRemove] omitted
  /// and [packagesToDemote] changed to `dependency: transitive`.
  /// Returns a tuple with the filtered content and the set of unexpected
  /// packages - package names that remain in the copy but are not listed in
  /// [expectedRemainingPackages].
  static (String, Set<String>) filter({
    required final String content,
    required final Set<String> packagesToRemove,
    required final Set<String> packagesToDemote,
    required final Set<String> expectedRemainingPackages,
  }) {
    final keptPackages = <String>[];
    final outputLines = <String>[_generatedByScloudLine];

    var inPackagesSection = false;
    var skippingPackage = false;
    var demotingPackage = false;
    var isFirstLine = true;

    for (final line in content.split('\n')) {
      if (isFirstLine) {
        isFirstLine = false;
        if (line == _generatedByPubLine) {
          continue;
        }
      }

      if (!inPackagesSection) {
        outputLines.add(line);
        if (_isPackagesSectionHeader(line)) {
          inPackagesSection = true;
        }
        continue;
      }

      final packageName = _packageNameFromHeader(line);
      if (packageName != null) {
        skippingPackage = packagesToRemove.contains(packageName);
        demotingPackage =
            !skippingPackage && packagesToDemote.contains(packageName);
        if (!skippingPackage) {
          keptPackages.add(packageName);
          outputLines.add(line);
        }
        continue;
      }

      if (_isTopLevelKey(line)) {
        skippingPackage = false;
        demotingPackage = false;
        inPackagesSection = false;
        outputLines.add(line);
        continue;
      }

      if (skippingPackage) {
        continue;
      }

      if (demotingPackage && _isDependencyLine(line)) {
        outputLines.add(_demotedDependencyLine);
        continue;
      }

      outputLines.add(line);
    }

    final output = outputLines.join('\n');
    final unexpectedPackages = keptPackages.toSet().difference(
      expectedRemainingPackages,
    );
    return (output, unexpectedPackages);
  }

  static bool _isPackagesSectionHeader(final String line) {
    return line.trimRight() == 'packages:';
  }

  static String? _packageNameFromHeader(final String line) {
    final match = _packageHeaderPattern.firstMatch(line);
    return match?.group(1);
  }

  static bool _isDependencyLine(final String line) {
    return line.startsWith('    dependency:');
  }

  static bool _isTopLevelKey(final String line) {
    if (line.isEmpty) {
      return false;
    }
    final first = line.codeUnitAt(0);
    return first != 0x20 /* space */ &&
        first != 0x09 /* tab */ &&
        first != 0x23 /* # */;
  }
}
