import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:serverpod_cloud_cli/util/package_graph/package_graph.dart';
import 'package:test/test.dart';

void main() {
  group('PubspecLockFilter.createFilteredCopy -', () {
    late Directory tempDir;
    late String outputFilePath;
    late File outputFile;

    setUp(() {
      tempDir = Directory.systemTemp.createTempSync('pubspec_lock_filter_');
      final outputFileName = 'filtered.lock';
      outputFilePath = p.join(tempDir.path, outputFileName);
      outputFile = File(outputFilePath);
    });

    tearDown(() {
      tempDir.deleteSync(recursive: true);
    });

    test('Given a pubspec.lock with packages to remove '
        'when creating a filtered copy '
        'then removed package lines are omitted and retained lines match', () {
      File(p.join(tempDir.path, 'pubspec.lock')).writeAsStringSync('''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  keep_a:
    dependency: "direct main"
    description:
      name: keep_a
      sha256: aaa
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  remove_me:
    dependency: transitive
    description:
      name: remove_me
      sha256: bbb
      url: "https://pub.dev"
    source: hosted
    version: "2.0.0"
  keep_b:
    dependency: transitive
    description:
      path: "packages/keep_b"
      relative: true
    source: path
    version: "0.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');

      final unexpected = PubspecLockFilter.createFilteredCopy(
        projectPath: tempDir.path,
        outputFilePath: outputFilePath,
        packagesToRemove: {'remove_me'},
        packagesToDemote: const {},
        expectedRemainingPackages: {'keep_a', 'keep_b'},
      );

      expect(unexpected, isEmpty);
      expect(outputFile.readAsStringSync(), '''
# Generated by scloud
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  keep_a:
    dependency: "direct main"
    description:
      name: keep_a
      sha256: aaa
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  keep_b:
    dependency: transitive
    description:
      path: "packages/keep_b"
      relative: true
    source: path
    version: "0.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');
    });

    test('Given packages to demote '
        'when creating a filtered copy '
        'then their dependency lines become transitive', () {
      File(p.join(tempDir.path, 'pubspec.lock')).writeAsStringSync('''
# Generated by pub
packages:
  keep_direct:
    dependency: "direct main"
    description:
      name: keep_direct
    source: hosted
    version: "1.0.0"
  demote_me:
    dependency: "direct dev"
    description:
      name: demote_me
    source: hosted
    version: "2.0.0"
  demote_overridden:
    dependency: "direct overridden"
    description:
      name: demote_overridden
    source: hosted
    version: "3.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');

      final unexpected = PubspecLockFilter.createFilteredCopy(
        projectPath: tempDir.path,
        outputFilePath: outputFilePath,
        packagesToRemove: const {},
        packagesToDemote: {'demote_me', 'demote_overridden'},
        expectedRemainingPackages: {
          'keep_direct',
          'demote_me',
          'demote_overridden',
        },
      );

      expect(unexpected, isEmpty);
      expect(outputFile.readAsStringSync(), '''
# Generated by scloud
packages:
  keep_direct:
    dependency: "direct main"
    description:
      name: keep_direct
    source: hosted
    version: "1.0.0"
  demote_me:
    dependency: transitive
    description:
      name: demote_me
    source: hosted
    version: "2.0.0"
  demote_overridden:
    dependency: transitive
    description:
      name: demote_overridden
    source: hosted
    version: "3.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');
    });

    test('Given packages to remove and demote '
        'when creating a filtered copy '
        'then removals and demotions are both applied', () {
      File(p.join(tempDir.path, 'pubspec.lock')).writeAsStringSync('''
packages:
  keep_me:
    dependency: "direct main"
    description:
      name: keep_me
    source: hosted
    version: "1.0.0"
  remove_me:
    dependency: "direct main"
    description:
      name: remove_me
    source: hosted
    version: "2.0.0"
  demote_me:
    dependency: "direct dev"
    description:
      name: demote_me
    source: hosted
    version: "3.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');

      final unexpected = PubspecLockFilter.createFilteredCopy(
        projectPath: tempDir.path,
        outputFilePath: outputFilePath,
        packagesToRemove: {'remove_me'},
        packagesToDemote: {'demote_me'},
        expectedRemainingPackages: {'keep_me', 'demote_me'},
      );

      expect(unexpected, isEmpty);
      expect(outputFile.readAsStringSync(), '''
# Generated by scloud
packages:
  keep_me:
    dependency: "direct main"
    description:
      name: keep_me
    source: hosted
    version: "1.0.0"
  demote_me:
    dependency: transitive
    description:
      name: demote_me
    source: hosted
    version: "3.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');
    });

    test('Given a pubspec.lock without a Generated by pub header '
        'when creating a filtered copy '
        'then Generated by scloud is still written first', () {
      File(p.join(tempDir.path, 'pubspec.lock')).writeAsStringSync('''
packages:
  alpha:
    dependency: transitive
    description:
      name: alpha
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');

      PubspecLockFilter.createFilteredCopy(
        projectPath: tempDir.path,
        outputFilePath: outputFilePath,
        packagesToRemove: const {},
        packagesToDemote: const {},
        expectedRemainingPackages: {'alpha'},
      );

      expect(outputFile.readAsStringSync(), '''
# Generated by scloud
packages:
  alpha:
    dependency: transitive
    description:
      name: alpha
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');
    });

    test('Given a filtered copy that still contains unexpected packages '
        'when creating a filtered copy '
        'then those package names are returned as a set', () {
      File(p.join(tempDir.path, 'pubspec.lock')).writeAsStringSync('''
packages:
  alpha:
    dependency: transitive
    description:
      name: alpha
    source: hosted
    version: "1.0.0"
  beta:
    dependency: transitive
    description:
      name: beta
    source: hosted
    version: "1.0.0"
  gamma:
    dependency: transitive
    description:
      name: gamma
    source: hosted
    version: "1.0.0"
  delta:
    dependency: transitive
    description:
      name: delta
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');

      final unexpected = PubspecLockFilter.createFilteredCopy(
        projectPath: tempDir.path,
        outputFilePath: outputFilePath,
        packagesToRemove: {'beta'},
        packagesToDemote: const {},
        expectedRemainingPackages: {'alpha'},
      );

      expect(unexpected, {'gamma', 'delta'});
    });

    test('Given a nested relative output path '
        'when creating a filtered copy '
        'then the file is written under the project directory', () {
      Directory(p.join(tempDir.path, '.scloud')).createSync();
      File(p.join(tempDir.path, 'pubspec.lock')).writeAsStringSync('''
packages:
  alpha:
    dependency: transitive
    description:
      name: alpha
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');

      final nestedOutputPath = p.join(tempDir.path, '.scloud', 'filtered.lock');
      final unexpected = PubspecLockFilter.createFilteredCopy(
        projectPath: tempDir.path,
        outputFilePath: nestedOutputPath,
        packagesToRemove: const {},
        packagesToDemote: const {},
        expectedRemainingPackages: {'alpha'},
      );

      expect(unexpected, isEmpty);
      expect(File(nestedOutputPath).readAsStringSync(), '''
# Generated by scloud
packages:
  alpha:
    dependency: transitive
    description:
      name: alpha
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');
    });

    test('Given nested description name fields '
        'when creating a filtered copy '
        'then nested name keys are not treated as package entries', () {
      File(p.join(tempDir.path, 'pubspec.lock')).writeAsStringSync('''
packages:
  foo:
    dependency: transitive
    description:
      name: foo
      sha256: abc
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
''');

      final unexpected = PubspecLockFilter.createFilteredCopy(
        projectPath: tempDir.path,
        outputFilePath: outputFilePath,
        packagesToRemove: {'foo'},
        packagesToDemote: const {},
        expectedRemainingPackages: const {},
      );

      expect(unexpected, isEmpty);
      expect(outputFile.readAsStringSync(), '''
# Generated by scloud
packages:
sdks:
  dart: ">=3.0.0 <4.0.0"
''');
    });

    test('Given a missing pubspec.lock '
        'when creating a filtered copy '
        'then a FormatException is thrown', () {
      expect(
        () => PubspecLockFilter.createFilteredCopy(
          projectPath: tempDir.path,
          outputFilePath: outputFilePath,
          packagesToRemove: const {},
          packagesToDemote: const {},
          expectedRemainingPackages: const {},
        ),
        throwsA(isA<FormatException>()),
      );
    });
  });
}
