import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:pub_semver/pub_semver.dart';
import 'package:serverpod_cloud_cli/commands/deploy/prepare_project_files.dart';
import 'package:serverpod_cloud_cli/util/dart_version_util.dart'
    show SupportedDartSdkPolicy;
import 'package:serverpod_cloud_cli/util/pubspec_validator.dart';
import 'package:test_descriptor/test_descriptor.dart' as d;
import 'package:test/test.dart';

import 'package:yaml_codec/yaml_codec.dart';

import '../test_utils/project_factory.dart' show ProjectFactory;
import '../test_utils/test_command_logger.dart' show TestCommandLogger;

void main() {
  final logger = TestCommandLogger();
  final supportedSdk = SupportedDartSdkPolicy(
    supportedRange: VersionConstraint.parse('>=3.8.0 <3.12.0'),
    supportedVersions: ['3.8', '3.9', '3.10', '3.11'],
    documentationUrl: Uri.parse(
      'https://docs.serverpod.dev/cloud/reference/dart-sdk-versions',
    ),
  );

  group('Given a complex workspace directory structure '
      'when preparing the workspace for deployment', () {
    late final ProjectFilePreparer projectFilePreparer;
    late final String filteredPubspecLock;

    setUpAll(() async {
      await d.dir('monorepo', [
        d.file('pubspec.yaml', '''
name: monorepo
environment:
  sdk: ${ProjectFactory.validSdkVersion}
  flutter: 3.29.0
workspace:
  - packages/dart_utilities
  - packages/flutter_utilities
  - project/project_server
  - project/project_client
  - project/project_app
'''),
        d.file('pubspec.lock', '''
# Generated by pub
packages:
  collection:
    dependency: "direct main"
    description:
      name: collection
      sha256: "1111111111111111111111111111111111111111111111111111111111111111"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.0"
  dart_utilities:
    dependency: "direct main"
    description:
      path: "packages/dart_utilities"
      relative: true
    source: path
    version: "1.0.0"
  flutter:
    dependency: transitive
    description: flutter
    source: sdk
    version: "0.0.0"
  flutter_utilities:
    dependency: "direct main"
    description:
      path: "packages/flutter_utilities"
      relative: true
    source: path
    version: "1.0.0"
  project_app:
    dependency: "direct main"
    description:
      path: "project/project_app"
      relative: true
    source: path
    version: "0.0.0"
  project_client:
    dependency: "direct main"
    description:
      path: "project/project_client"
      relative: true
    source: path
    version: "1.0.0"
  project_server:
    dependency: "direct main"
    description:
      path: "project/project_server"
      relative: true
    source: path
    version: "0.0.0"
  serverpod:
    dependency: "direct main"
    description:
      name: serverpod
      sha256: "0000000000000000000000000000000000000000000000000000000000000000"
      url: "https://pub.dev"
    source: hosted
    version: "2.9.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
'''),
        d.dir('.dart_tool', [
          d.file('package_graph.json', '''
{
  "configVersion": 1,
  "roots": [
    "monorepo",
    "dart_utilities",
    "flutter_utilities",
    "project_server",
    "project_client",
    "project_app"
  ],
  "packages": [
    {
      "name": "monorepo",
      "version": "0.0.0",
      "dependencies": ["collection"],
      "devDependencies": []
    },
    {
      "name": "dart_utilities",
      "version": "1.0.0",
      "dependencies": ["collection"],
      "devDependencies": []
    },
    {
      "name": "flutter_utilities",
      "version": "1.0.0",
      "dependencies": ["flutter"],
      "devDependencies": []
    },
    {
      "name": "project_server",
      "version": "0.0.0",
      "dependencies": ["serverpod", "dart_utilities"],
      "devDependencies": []
    },
    {
      "name": "project_client",
      "version": "1.0.0",
      "dependencies": [],
      "devDependencies": []
    },
    {
      "name": "project_app",
      "version": "0.0.0",
      "dependencies": ["project_client", "flutter_utilities"],
      "devDependencies": []
    },
    {
      "name": "serverpod",
      "version": "2.9.0",
      "dependencies": [],
      "devDependencies": []
    },
    {
      "name": "flutter",
      "version": "0.0.0",
      "dependencies": [],
      "devDependencies": []
    },
    {
      "name": "collection",
      "version": "1.19.0",
      "dependencies": [],
      "devDependencies": []
    }
  ]
}
'''),
        ]),
        d.dir('packages', [
          d.dir('dart_utilities', [
            d.file('pubspec.yaml', '''
name: dart_utilities
version: 1.0.0
environment:
  sdk: ${ProjectFactory.validSdkVersion}
resolution: workspace
'''),
          ]),
          d.dir('flutter_utilities', [
            d.file('pubspec.yaml', '''
name: flutter_utilities
version: 1.0.0
environment:
  sdk: ${ProjectFactory.validSdkVersion}
  flutter: 3.29.0
resolution: workspace
'''),
          ]),
        ]),
        d.dir('project', [
          d.dir('project_server', [
            d.file('pubspec.yaml', '''
name: project_server
environment:
  sdk: ${ProjectFactory.validSdkVersion}
resolution: workspace
dependencies:
  serverpod: ${ProjectFactory.validServerpodVersion}
  dart_utilities: ^1.0.0
'''),
          ]),
          d.dir('project_client', [
            d.file('pubspec.yaml', '''
name: project_client
version: 1.0.0
environment:
  sdk: ${ProjectFactory.validSdkVersion}
resolution: workspace
'''),
          ]),
          d.dir('project_app', [
            d.file('pubspec.yaml', '''
name: project_app
environment:
  sdk: ${ProjectFactory.validSdkVersion}
  flutter: 3.29.0
resolution: workspace
dependencies:
  project_client: ^1.0.0
  flutter_utilities: ^1.0.0
'''),
          ]),
        ]),
      ]).create();

      logger.clear();

      final projectDirectory = Directory(
        p.join(d.sandbox, 'monorepo', 'project', 'project_server'),
      );
      projectFilePreparer = TenantProject.prepare(
        projectDirectory,
        supportedSdkPolicy: supportedSdk,
        tenantProjectPubspec: TenantProjectPubspec.fromProjectDir(
          projectDirectory,
        ),
      );

      final lockContent = File(
        p.join(d.sandbox, 'monorepo', 'pubspec.lock'),
      ).readAsStringSync();
      filteredPubspecLock = projectFilePreparer.filterPubspecLock(lockContent);
    });

    test('then the correct workspace root directory is found', () async {
      expect(
        projectFilePreparer.rootDirectory.path,
        equals(p.join(d.sandbox, 'monorepo')),
      );
    });

    test('then the preparer is marked as a workspace', () async {
      expect(projectFilePreparer.isWorkspace, isTrue);
    });

    test('then the correct included package paths are returned', () async {
      expect(
        projectFilePreparer.includedPackagePaths,
        containsAll(['packages/dart_utilities', 'project/project_server']),
      );
    });

    test('then the included subpaths include packages and .scloud', () async {
      expect(
        projectFilePreparer.includedSubPaths,
        containsAll([
          'packages/dart_utilities',
          'project/project_server',
          '.scloud',
        ]),
      );
    });

    test('then .scloud/scloud_server_dir file is created.', () async {
      final descriptor = d.dir('.scloud', [
        d.file('scloud_server_dir', 'project/project_server'),
      ]);

      await expectLater(
        descriptor.validate(p.join(d.sandbox, 'monorepo')),
        completes,
      );
    });

    test('then .scloud/scloud_ws_pubspec.yaml is not created', () async {
      final scloudRootPubspec = File(
        p.join(d.sandbox, 'monorepo', '.scloud', 'scloud_ws_pubspec.yaml'),
      );
      expect(scloudRootPubspec.existsSync(), isFalse);
    });

    test('then filterPubspecLock retains packages reachable '
        'from the server package', () async {
      expect(
        filteredPubspecLock,
        stringContainsInOrder(['# Generated by scloud', 'packages:']),
      );

      final packages =
          (yamlDecode(filteredPubspecLock) as Map)['packages'] as Map;

      expect(
        packages.keys,
        containsAll([
          'project_server',
          'dart_utilities',
          'serverpod',
          'collection',
        ]),
      );
    });

    test('then filterPubspecLock omits packages unreachable '
        'from the server package', () async {
      final packages =
          (yamlDecode(filteredPubspecLock) as Map)['packages'] as Map;

      expect(packages.containsKey('flutter'), isFalse);
      expect(packages.containsKey('flutter_utilities'), isFalse);
      expect(packages.containsKey('project_app'), isFalse);
      expect(packages.containsKey('project_client'), isFalse);
    });

    test('then filterPubspecLock demotes packages that are no '
        'longer direct root dependencies to transitive', () async {
      final packages =
          (yamlDecode(filteredPubspecLock) as Map)['packages'] as Map;

      expect(packages['collection'], containsPair('dependency', 'transitive'));
      expect(
        packages['dart_utilities'],
        containsPair('dependency', 'direct main'),
      );
      expect(packages['serverpod'], containsPair('dependency', 'direct main'));
    });
  });

  group('Given a workspace with an obsolete .scloud/scloud_ws_pubspec.yaml '
      'when preparing the workspace for deployment', () {
    late final String monorepoPath;

    setUpAll(() async {
      await d.dir('monorepo', [
        d.file('pubspec.yaml', '''
name: monorepo
environment:
  sdk: ${ProjectFactory.validSdkVersion}
workspace:
  - project/project_server
'''),
        d.file('pubspec.lock', '''
# Generated by pub
packages:
  project_server:
    dependency: "direct main"
    description:
      path: "project/project_server"
      relative: true
    source: path
    version: "0.0.0"
  serverpod:
    dependency: "direct main"
    description:
      name: serverpod
      sha256: "0000000000000000000000000000000000000000000000000000000000000000"
      url: "https://pub.dev"
    source: hosted
    version: "2.9.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
'''),
        d.dir('.dart_tool', [
          d.file('package_graph.json', '''
{
  "configVersion": 1,
  "roots": ["monorepo", "project_server"],
  "packages": [
    {
      "name": "monorepo",
      "version": "0.0.0",
      "dependencies": [],
      "devDependencies": []
    },
    {
      "name": "project_server",
      "version": "0.0.0",
      "dependencies": ["serverpod"],
      "devDependencies": []
    },
    {
      "name": "serverpod",
      "version": "2.9.0",
      "dependencies": [],
      "devDependencies": []
    }
  ]
}
'''),
        ]),
        d.dir('.scloud', [
          d.file('scloud_ws_pubspec.yaml', '''
name: monorepo
environment:
  sdk: ${ProjectFactory.validSdkVersion}
workspace:
  - project/project_server
'''),
        ]),
        d.dir('project', [
          d.dir('project_server', [
            d.file('pubspec.yaml', '''
name: project_server
environment:
  sdk: ${ProjectFactory.validSdkVersion}
resolution: workspace
dependencies:
  serverpod: ${ProjectFactory.validServerpodVersion}
'''),
          ]),
        ]),
      ]).create();

      monorepoPath = p.join(d.sandbox, 'monorepo');

      final obsoletePubspec = File(
        p.join(monorepoPath, '.scloud', 'scloud_ws_pubspec.yaml'),
      );
      expect(obsoletePubspec.existsSync(), isTrue);

      final projectDirectory = Directory(
        p.join(monorepoPath, 'project', 'project_server'),
      );
      TenantProject.prepare(
        projectDirectory,
        supportedSdkPolicy: supportedSdk,
        tenantProjectPubspec: TenantProjectPubspec.fromProjectDir(
          projectDirectory,
        ),
      );
    });

    test('then the obsolete .scloud/scloud_ws_pubspec.yaml is deleted', () {
      final obsoletePubspec = File(
        p.join(monorepoPath, '.scloud', 'scloud_ws_pubspec.yaml'),
      );
      expect(obsoletePubspec.existsSync(), isFalse);
    });

    test('then .scloud/scloud_server_dir file is still created', () async {
      final descriptor = d.dir('.scloud', [
        d.file('scloud_server_dir', 'project/project_server'),
      ]);

      await expectLater(descriptor.validate(monorepoPath), completes);
    });
  });

  group('Given a non-workspace server project '
      'when preparing for deployment', () {
    late final ProjectFilePreparer projectFilePreparer;
    late final Directory projectDirectory;
    late final String filteredPubspecLock;

    setUpAll(() async {
      await ProjectFactory.serverpodServerDir(
        contents: [
          d.file('pubspec.lock', '''
# Generated by pub
packages:
  collection:
    dependency: "direct main"
    description:
      name: collection
      sha256: "1111111111111111111111111111111111111111111111111111111111111111"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.0"
  orphan_package:
    dependency: "direct dev"
    description:
      name: orphan_package
      sha256: "2222222222222222222222222222222222222222222222222222222222222222"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.0"
  serverpod:
    dependency: "direct main"
    description:
      name: serverpod
      sha256: "0000000000000000000000000000000000000000000000000000000000000000"
      url: "https://pub.dev"
    source: hosted
    version: "2.9.0"
sdks:
  dart: ">=3.0.0 <4.0.0"
'''),
          d.dir('.dart_tool', [
            d.file('package_graph.json', '''
{
  "configVersion": 1,
  "roots": ["${ProjectFactory.defaultPackageName}"],
  "packages": [
    {
      "name": "${ProjectFactory.defaultPackageName}",
      "version": "0.0.0",
      "dependencies": ["serverpod", "collection"],
      "devDependencies": ["orphan_package"]
    },
    {
      "name": "serverpod",
      "version": "2.9.0",
      "dependencies": [],
      "devDependencies": []
    },
    {
      "name": "collection",
      "version": "1.19.0",
      "dependencies": [],
      "devDependencies": []
    },
    {
      "name": "orphan_package",
      "version": "1.0.0",
      "dependencies": [],
      "devDependencies": []
    }
  ]
}
'''),
          ]),
        ],
      ).create();

      logger.clear();

      projectDirectory = Directory(
        p.join(d.sandbox, ProjectFactory.defaultDirectoryName),
      );
      projectFilePreparer = TenantProject.prepare(
        projectDirectory,
        supportedSdkPolicy: supportedSdk,
        tenantProjectPubspec: TenantProjectPubspec.fromProjectDir(
          projectDirectory,
        ),
      );

      final lockContent = File(
        p.join(projectDirectory.path, 'pubspec.lock'),
      ).readAsStringSync();
      filteredPubspecLock = projectFilePreparer.filterPubspecLock(lockContent);
    });

    test('then the preparer is not marked as a workspace', () async {
      expect(projectFilePreparer.isWorkspace, isFalse);
    });

    test('then the project directory is used as the root', () async {
      expect(
        projectFilePreparer.rootDirectory.path,
        equals(projectDirectory.path),
      );
    });

    test('then the project package name is set', () async {
      expect(
        projectFilePreparer.projectPackageName,
        equals(ProjectFactory.defaultPackageName),
      );
    });

    test('then the included subpaths are the project root only', () async {
      expect(projectFilePreparer.includedSubPaths, equals(['.']));
    });

    test('then no workspace package paths are included', () async {
      expect(projectFilePreparer.includedPackagePaths, isEmpty);
    });

    test('then no .scloud deployment files are created', () async {
      final scloudDir = Directory(p.join(projectDirectory.path, '.scloud'));
      expect(scloudDir.existsSync(), isFalse);
    });

    test('then filterPubspecYaml strips dev_dependencies', () async {
      final filtered = projectFilePreparer.filterPubspecYaml('''
name: ${ProjectFactory.defaultPackageName}
environment:
  sdk: ${ProjectFactory.validSdkVersion}
dependencies:
  serverpod: ${ProjectFactory.validServerpodVersion}
dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
''');

      final doc = yamlDecode(filtered);
      expect(doc, isA<Map>());
      expect((doc as Map).containsKey('dev_dependencies'), isFalse);
      expect(doc, containsPair('name', ProjectFactory.defaultPackageName));
      expect(doc, containsPair('dependencies', isNotEmpty));
    });

    test('then filterPubspecYaml leaves content without '
        'dev_dependencies unchanged', () async {
      final content =
          '''
name: ${ProjectFactory.defaultPackageName}
environment:
  sdk: ${ProjectFactory.validSdkVersion}
dependencies:
  serverpod: ${ProjectFactory.validServerpodVersion}
''';
      expect(projectFilePreparer.filterPubspecYaml(content), equals(content));
    });

    test('then filterPubspecLock retains packages reachable '
        'from the project package', () async {
      expect(
        filteredPubspecLock,
        stringContainsInOrder(['# Generated by scloud', 'packages:']),
      );

      final packages =
          (yamlDecode(filteredPubspecLock) as Map)['packages'] as Map;

      expect(packages.keys, containsAll(['serverpod', 'collection']));
    });

    test('then filterPubspecLock omits packages only reachable '
        'as dev dependencies', () async {
      final packages =
          (yamlDecode(filteredPubspecLock) as Map)['packages'] as Map;

      expect(packages.containsKey('orphan_package'), isFalse);
    });
  });

  group(
    'Given a workspace directory structure with an indirect flutter dependency '
    'when preparing the workspace for deployment',
    () {
      setUpAll(() async {
        await d.dir('monorepo', [
          d.file('pubspec.yaml', '''
name: monorepo
environment:
  sdk: ${ProjectFactory.validSdkVersion}
  flutter: 3.29.0
workspace:
  - packages/flutter_utilities
  - project/project_server
'''),
          d.dir('packages', [
            d.dir('flutter_utilities', [
              d.file('pubspec.yaml', '''
name: flutter_utilities
version: 1.0.0
environment:
  sdk: ${ProjectFactory.validSdkVersion}
  flutter: 3.29.0
resolution: workspace
'''),
            ]),
          ]),
          d.dir('project', [
            d.dir('project_server', [
              d.file('pubspec.yaml', '''
name: project_server
environment:
  sdk: ${ProjectFactory.validSdkVersion}
resolution: workspace
dependencies:
  serverpod: ${ProjectFactory.validServerpodVersion}
  flutter_utilities: ^1.0.0
'''),
            ]),
          ]),
        ]).create();
      });

      setUp(() {
        logger.clear();
      });

      task(final String baseDir) {
        final projectDirectory = Directory(
          p.join(baseDir, 'monorepo', 'project', 'project_server'),
        );
        return TenantProject.prepare(
          projectDirectory,
          supportedSdkPolicy: supportedSdk,
          tenantProjectPubspec: TenantProjectPubspec.fromProjectDir(
            projectDirectory,
          ),
        );
      }

      test('then command throws WorkspaceException.', () async {
        expect(
          () => task(d.sandbox),
          throwsA(
            isA<WorkspaceException>().having(
              (final e) => e.errors,
              'errors',
              equals([
                'A Flutter dependency is not allowed in a server package: flutter_utilities',
              ]),
            ),
          ),
        );
      });
    },
  );

  group('Given a workspace package with missing workspace root', () {
    setUpAll(() async {
      logger.clear();

      await d.dir('monorepo', [
        d.dir('packages', [
          d.dir('dart_utilities', [
            d.file('pubspec.yaml', '''
name: dart_utilities
version: 1.0.0
environment:
  sdk: ${ProjectFactory.validSdkVersion}
resolution: workspace
'''),
          ]),
        ]),
        d.dir('project', [
          d.dir('project_server', [
            d.file('pubspec.yaml', '''
name: project_server
environment:
  sdk: ${ProjectFactory.validSdkVersion}
resolution: workspace
dependencies:
  serverpod: ${ProjectFactory.validServerpodVersion}
  dart_utilities: ^1.0.0
'''),
          ]),
        ]),
      ]).create();
    });

    setUp(() {
      logger.clear();
    });

    task(final String baseDir) {
      final projectDirectory = Directory(
        p.join(baseDir, 'monorepo', 'project', 'project_server'),
      );
      return TenantProject.prepare(
        projectDirectory,
        supportedSdkPolicy: supportedSdk,
        tenantProjectPubspec: TenantProjectPubspec.fromProjectDir(
          projectDirectory,
        ),
      );
    }

    test('then command throws WorkspaceException.', () async {
      expect(
        () => task(d.sandbox),
        throwsA(
          isA<WorkspaceException>().having(
            (final e) => e.errors,
            'errors',
            equals([
              'Could not find the workspace root directory.',
              'Ensure the project is part of a valid Dart workspace.',
            ]),
          ),
        ),
      );
    });
  });
}
