include: package:serverpod_cloud_lints/lints.yaml

# Consider making changes in the common lints package instead of here,
# unless it is specifically a local need.

linter:
  rules:
    avoid_print: false
