name: serverpod_cloud_cli
version: 0.0.1
description: A CLI tool from Serverpod used to deploy and manage Serverpod Cloud projects.
repository: https://github.com/serverpod/serverpod_cloud_clients
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod_cloud_clients/issues

topics:
  - cli
  - serverpod
  - cloud

environment:
  sdk: ">=3.6.0 <3.7.0"

dependencies:
  archive: ^3.6.1
  args: ^2.5.0
  cli_tools: ^0.1.4
  collection: ^1.19.0
  path: ^1.8.2
  pool: ^1.5.1
  pub_semver: ^2.1.4
  serverpod_ground_control_client: ^0.0.1
  yaml: ^3.1.2
  basic_utils: ^5.7.0

dev_dependencies:
  googleapis: ^13.2.0
  http: ^1.2.2
  test: ^1.24.0
  uuid: ^4.1.0
  meta: ^1.16.0
  mocktail: ^1.0.4
executables:
  scloud: serverpod_cloud_cli
