name: serverpod_cloud_cli
version: 0.11.1
description: A CLI tool from Serverpod used to deploy and manage Serverpod Cloud projects.
repository: https://github.com/serverpod/serverpod_cloud_clients
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod_cloud_clients/issues

topics:
  - cli
  - serverpod
  - cloud

environment:
  # Note, this range must include all the supported customer Dart SDK versions.
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  archive: ^3.6.1
  args: ^2.6.0
  basic_utils: ^5.7.0
  cli_tools: ^0.7.0
  collection: ^1.19.0
  config: ^0.7.0
  meta: ^1.16.0
  path: ^1.8.2
  pool: ^1.5.1
  pub_semver: ^2.1.0
  pubspec_parse: ^1.5.0
  ground_control_client: ^0.11.0
  rfc_6901: ^0.2.0
  yaml_codec: ^1.0.0
  yaml: ^3.1.0
  email_validator: ^3.0.0
  dio: ^5.8.0+1

dev_dependencies:
  http: ^1.2.2
  test: ^1.24.0
  uuid: ^4.1.0
  mocktail: ^1.0.4
  test_descriptor: ^2.0.0

executables:
  scloud: serverpod_cloud_cli
