name: serverpod_cloud_cli
version: 0.0.1
description: A CLI tool from Serverpod used to deploy and manage Serverpod Cloud projects.
repository: https://github.com/serverpod/serverpod_cloud_clients
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod_cloud_clients/issues

topics:
  - cli
  - serverpod
  - cloud

environment:
  sdk: ">=3.1.0 <4.0.0"


dependencies:
  cli_tools: ^0.1.0
  pub_semver: ^2.1.4

dev_dependencies:
  test: ^1.24.0
  serverpod_lints: ">=1.2.6"

executables:
  scloud: serverpod_cloud_cli
