name: serverpod_cloud_cli
version: 0.0.1
description: A CLI tool from Serverpod used to deploy and manage Serverpod Cloud projects.
repository: https://github.com/serverpod/serverpod_cloud_clients
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod_cloud_clients/issues

topics:
  - cli
  - serverpod
  - cloud

environment:
  sdk: ">=3.3.0 <4.0.0"


dependencies:
  archive: ^3.6.1  
  cli_tools: ^0.1.0
  path: ^1.8.2
  pool: ^1.5.1
  pub_semver: ^2.1.4
  serverpod_ground_control_client: ^0.0.1

dev_dependencies:
  googleapis: ^13.2.0
  http: ^1.2.2
  serverpod_lints: ">=1.2.6"
  test: ^1.24.0
  uuid: ^4.1.0

executables:
  scloud: serverpod_cloud_cli
