name: serverpod_ground_control_client
version: 0.0.1
description: A client library for the Serverpod Ground Control API. Used to manage Serverpod Cloud projects.
repository: https://github.com/serverpod/serverpod_ground_control_client
homepage: https://serverpod.dev
issue_tracker: https://github.com/serverpod/serverpod_ground_control_client/issues

topics:
  - api
  - client

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  serverpod_client: 2.0.0-alpha.2
  serverpod_auth_client: 2.0.0-alpha.2 
