name: Publish cli

on:
  push:
    tags:
      - 'serverpod_cloud_cli-v[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]*'
      - 'serverpod_cloud_cli-v[0-9]+.[0-9]+.[0-9]'
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        run: dart pub get
        working-directory: serverpod_cloud_cli
      - name: Publish
        run: dart pub publish -force --skip-validation
        working-directory: serverpod_cloud_cli
