name: serverpod_cloud_shared
description: Shared logic between Serverpod Cloud server and its clients.
version: 0.1.1
repository: https://github.com/serverpod/serverpod_cloud_clients
homepage: https://serverpod.dev/
issue_tracker: https://github.com/serverpod/serverpod_cloud_clients/issues

environment:
  # Note, this range must include all the supported customer Dart SDK versions.
  sdk: ">=3.10.3 <4.0.0"


dependencies:
  dio: ^5.8.0+1
  http: ^1.2.2

dev_dependencies:
  test: ^1.25.6
